title: حسین نقدبیشی
author: حسین نقدبیشی
author_link: https://naghdbishi.ir/
author_description: An economist-to-be
description: A blog about economics, technology, free software and other topics, written by Hosein Nahghdbishi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://khoone.naghdbishi.ir/" # the base hostname & protocol for your site
lang: fa_IR

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: true


# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5
excerpt_separator: <!--more-->
# Sass
sass:
    style: :compressed

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
